Integrate Jamari's components
PongoAI/pongoai-frontend pull request #322
Opened 2021-11-26 02:38 UTC by jamari-morrison

#### Pull Request checklist

- [] Addresses an issue: Fixes #0000

#### Description of changes

Integrated the send section, review panel, and review timeline.  Added a temp workaround with "noImplicitAny": false in the tsx config.  Review panel and review timeline need to be able to have their width shortened past the current min width to render as  seen in the figma.

2021-11-26 04:05 UTC, czearing requested changes
Thanks for doing this! I did a quick review and left a few comments on the pr. They mainly cover addressing the inline styles, inline functions, and converting the pngs to svgs.

2021-11-26 04:07 UTC, czearing commented on packages/pongo-site/src/components/ReviewPanel/ReviewCard.tsx
> +    <div style={{ width: '100%', height: 'auto', display: 'flex', flexDirection: 'column' }}>
Let avoid inline styles altogether. This should be moved outside of the function in a const or alternatively in a CSS file

2021-11-26 04:09 UTC, czearing commented on packages/pongo-site/src/components/ReviewPanel/ReviewCard.tsx
> +                console.log('html clicked');
Let's avoid Inline functions. They should all be moved outside to avoid them from being recreated every render.

2021-11-26 04:10 UTC, czearing commented on packages/pongo-site/src/components/ReviewPanel/ReviewCard.tsx
> +              src="/twitter-icon.png"
These should be svgs and not pngs. An example of implementation can be found in the Dashboardcard

2021-11-26 04:12 UTC, czearing commented on packages/pongo-site/src/components/ReviewPanel/ReviewPanel.tsx
> +            { value: 'All', label: 'All Fields' },
Option arrays could be moved outside within a const called `FilterSearchOptions`

2021-11-26 04:18 UTC, czearing commented on packages/pongo-site/tsconfig.json
> +    "noImplicitAny": false
Let's not remove this from the tsconfig. If an implicit `any` is being cast and no other types seem to be compatible, it can directly be cast as an any resolving any build errors. Ideally, we should avoid casting as `any` but since we are prioritizing on time I think it should be fine for now to do so and they can be addressed later

2021-11-28 18:36 UTC, jamari-morrison commented on packages/pongo-site/src/components/ReviewPanel/ReviewCard.tsx
> +              src="/twitter-icon.png"
I swapped all the pngs to the svgs in figma except for the customer profile photo, as I assume we'll still be getting that from some sort of email api as a png

2021-11-28 18:36 UTC, jamari-morrison commented on packages/pongo-site/tsconfig.json
> +    "noImplicitAny": false
Went with casting everything to "any" and added a backlog task for me to properly handle casting

2021-11-28 18:38 UTC, jamari-morrison commented on packages/pongo-site/src/components/ReviewPanel/ReviewCard.tsx
> +                console.log('html clicked');
Removed most of the inline functions, the ones left were necessary since they were on components generated with a .map() function and therefore may need to be recreated on render

2021-11-28 22:52 UTC, merged